name: flutter_music_player
description: 网抑云
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayer:
    path: ./audioplayer
  flutter_swiper: ^1.1.6
  cached_network_image: ^3.0.0
  video_player: ^2.1.1
  crypto: ^3.0.1
  connectivity: ^3.0.3 
  orientation: ^1.3.0
  sqflite: ^2.0.0+3
  dio: ^4.0.0
  fluttertoast: ^8.0.6
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  flutter_screenutil: 5.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/leftmenu/
    - assets/json/
    - assets/music/bgm.mp3

  fonts:
    - family: myIcon    #指定一个字体名
      fonts:
        - asset: assets/fonts/iconfont.ttf
